query PostQuery($uri: String!) {
  data: nodeByUri(uri: $uri) {
    id
    ... on Post {
      id
      content
      date
      title
      author {
        node {
          name
          avatar {
            url
          }
          uri
        }
      }
      categories {
        nodes {
          id
          name
          uri
        }
      }
      comments {
        nodes {
          link
          uri
          date
          id
          content
          author {
            node {
              name
              url
              avatar {
                url
              }
            }
          }
        }
      }
      featuredImage {
        node {
          title
          sourceUrl
        }
      }
    }
    ... on Page {
      id
      content
      date
      title
      author {
        node {
          name
          avatar {
            url
          }
          uri
        }
      }
      comments {
        nodes {
          link
          uri
          date
          id
          content
          author {
            node {
              name
              url
              avatar {
                url
              }
            }
          }
        }
      }
      featuredImage {
        node {
          title
          sourceUrl
        }
      }
    }
  }
}

query GetPosts ($first: Int, $after: String) {
  posts(first: $first, after: $after) {
    pageInfo {
      endCursor
      hasNextPage
    }
    list: edges {
      article: node {
        id
        title
        uri
        excerpt
        featuredImage {
          node {
            sourceUrl
            altText
          }
        }
      }
    }
  }
}